export function lans() {
    return {
        en: {
            country: "English",
            loadcanvasText: "Analyzing...",
            loadMore: "Show Me More!",
            areYouSure: "Watch the result?",
            okResult: "OK",
            cancleResult: "Cancel",
            recommendText: " Other popular quizzes",
            shareFb: "Share",
            replay: "Try Again",
            genderMale: "Male",
            genderFemale: "Female"
        },
        es: {
            country: "Español",
            loadcanvasText: "Analizando...",
            loadMore: "¡Enséñame más!",
            areYouSure: "Ver resultado?",
            recommendText: "Otros test populares",
            shareFb: "Compartir",
            replay: "Inténtalo de nuevo",
            genderMale: "Hombre",
            genderFemale: "Mujer"
        },
        id: {
            country: "Indonesia",
            loadcanvasText: "Menganalisa...",
            loadMore: "Kasih liat yg lainnya!",
            areYouSure: "Watch the result?",
            recommendText: "kuis viral lainnya",
            shareFb: "Bagikan",
            replay: "Coba lagi",
            genderMale: "Cowok",
            genderFemale: "Cewek"
        },
        zh_TW: {
            country: "繁體中文",
            loadcanvasText: "分析中...",
            loadMore: "展示更多!",
            areYouSure: "確定觀看結果嗎?",
            okResult: "查看結果",
            cancleResult: "取消",
            recommendText: "受歡迎的題目",
            shareFb: "Facebook分享",
            replay: "再試一次",
            genderMale: "男",
            genderFemale: "女"
        },
        zh: {
            country: "繁體中文",
            loadcanvasText: "分析中...",
            loadMore: "展示更多!",
            areYouSure: "Watch the result?",
            recommendText: "其他受歡迎的測試",
            shareFb: "Facebook分享",
            replay: "再試一次",
            genderMale: "男",
            genderFemale: "女"
        },
        fr: {
            country: "Français",
            loadcanvasText: "L'analyse est en cours",
            loadMore: "Afficher plus !",
            areYouSure: "Watch the result?",
            recommendText: "Autres quizz populaires",
            shareFb: "Partager",
            replay: "Réessayer",
            genderMale: "Homme",
            genderFemale: "Femme"
        },
        it: {
            country: "Italiano",
            loadcanvasText: "Analisi in corso...",
            loadMore: "Mostrami altro!",
            areYouSure: "Watch the result?",
            recommendText: "Altri quiz popolari",
            shareFb: "Condividi",
            replay: "Prova di nuovo",
            genderMale: "Uomo",
            genderFemale: "Donna"
        },
        nl: {
            country: "Nederlands",
            loadcanvasText: "Aan het analyseren...",
            loadMore: "Laat me meer zien!",
            areYouSure: "Watch the result?",
            recommendText: "Andere populaire quizzen",
            shareFb: "Delen",
            replay: "Probeer het opnieuw",
            genderMale: "Man",
            genderFemale: "Vrouw"
        },
        pt: {
            country: "Português",
            loadcanvasText: "Analizando",
            loadMore: "Quero ver mais!",
            areYouSure: "Watch the result?",
            recommendText: "Outros quizzes populares",
            shareFb: "Compartilhar",
            replay: "Tente de novo",
            genderMale: "Masculino",
            genderFemale: "Feminino"
        },
        ms: {
            country: "Bahasa Melayu",
            loadcanvasText: "Menganalisis…",
            loadMore: "Tunjuk Saya Lagi!",
            areYouSure: "Watch the result?",
            recommendText: "Kuiz popular yang lain",
            shareFb: "Kongsi",
            replay: "Cuba lagi",
            genderMale: "Lelaki",
            genderFemale: "Perempuan"
        },
        hi: {
            country: "हिंदी",
            loadcanvasText: "विश्लेषण हो रहा है",
            loadMore: "और दिखाए",
            areYouSure: "Watch the result?",
            recommendText: "अन्य लोकप्रिय क्विज़",
            shareFb: "साझा करें",
            replay: "दुबारा खेले",
            genderMale: "पुरुष ",
            genderFemale: "महिला"
        },
        te: {
            country: "తెలుగు",
            loadcanvasText: "విశ్లేషణ చెయ్యబడుతుంది...",
            loadMore: "ఇంకా చూపించు!",
            areYouSure: "Watch the result?",
            recommendText: "ఇతర ప్రముఖ క్విజ్ లు",
            shareFb: "షేర్",
            replay: "మరలా ప్రయత్నించండి",
            genderMale: "మగ",
            genderFemale: "ఆడ"
        },
        ar: {
            country: "العربية",
            loadcanvasText: "جارٍ التحليل...",
            loadMore: "اعرض لي المزيد!",
            areYouSure: "Watch the result?",
            recommendText: "اختبارات شائعة اخرى",
            shareFb: "مشاركة",
            replay: "حاول مرة أخرى",
            genderMale: "ذكر",
            genderFemale: "أنثى"
        },
        th: {
            country: "ไทย",
            loadcanvasText: "กำลังวิเคราะห์...",
            loadMore: "โชว์เพิ่งเติม!",
            areYouSure: "Watch the result?",
            recommendText: "ควิซยอดนิยมอื่นๆ ",
            shareFb: "แชร์",
            replay: "ลองอีกครั้ง",
            genderMale: "ชาย",
            genderFemale: "หญิง"
        },
        hu: {
            country: "Magyar",
            loadcanvasText: "Elemzés...",
            loadMore: "Mutass nekem többet!",
            areYouSure: "Watch the result?",
            recommendText: "egyéb népszerű kvízek",
            shareFb: "Megosztás",
            replay: "Próbáld meg újra",
            genderMale: "Férfi",
            genderFemale: "Nő"
        },
        ru: {
            country: "Русский",
            loadcanvasText: "Анализ...",
            loadMore: "Показать мне еще!",
            areYouSure: "Watch the result?",
            recommendText: "другие популярные тесты",
            shareFb: "Поделиться",
            replay: "Повторить попытку",
            genderMale: "Мужчина",
            genderFemale: "Женщина"
        },
        ro: {
            country: "Română",
            loadcanvasText: "Se analizează...",
            loadMore: "Arată-mi mai mult!",
            areYouSure: "Watch the result?",
            recommendText: "Alte teste populare",
            shareFb: "Distribuie",
            replay: "Încearcă din nou",
            genderMale: "Bărbat",
            genderFemale: "Femeie"
        },
        bn: {
            country: "বাংলা",
            loadcanvasText: "বিশ্লেষণ চলছে...",
            loadMore: "আমাকে আরও দেখান!",
            areYouSure: "Watch the result?",
            recommendText: "অন্যান্য জনপ্রিয় কুইজসমূহ",
            shareFb: "শেয়ার করুন",
            replay: "আবার চেষ্টা করুন",
            genderMale: "পুরুষ",
            genderFemale: "নারী"
        },
        de: {
            country: "Deutsch",
            loadcanvasText: "Analysiere...",
            loadMore: "Zeig mir mehr!",
            areYouSure: "Watch the result?",
            recommendText: "Andere beliebte Ratespiele",
            shareFb: "Teilen",
            replay: "Erneut versuchen",
            genderMale: "Männlich",
            genderFemale: "Weiblich"
        },
        ia: {
            country: "English",
            loadcanvasText: "Analyzing...",
            loadMore: "Show Me More!",
            areYouSure: "Watch the result?",
            recommendText: "Other popular quizzes",
            shareFb: "Share",
            replay: "Try Again",
            genderMale: "Male",
            genderFemale: "Female"
        },
        vi: {
            country: "Tiếng Việt",
            loadcanvasText: "Đang phân tích...",
            loadMore: "Hiển Thị Thêm!",
            areYouSure: "Watch the result?",
            recommendText: "các câu hỏi phổ biến khác",
            shareFb: "Chia sẻ",
            replay: "Thử lại ",
            genderMale: "Nam",
            genderFemale: "Nữ"
        },
        tr: {
            country: "Türkçe",
            loadcanvasText: "Analiz ediliyor...",
            loadMore: "Bana Daha Fazlasını Göster!",
            areYouSure: "Watch the result?",
            recommendText: "Diğer popüler quiz’ler",
            shareFb: " Paylaş",
            replay: "Tekrar Dene ",
            genderMale: "Erkek",
            genderFemale: "Kadın"
        },
        pl: {
            country: "Polski",
            loadcanvasText: "Analizowanie...",
            loadMore: "Pokaż mi więcej!",
            areYouSure: "Watch the result?",
            recommendText: "Inne popularne quizy",
            shareFb: "Udostępnij",
            replay: "Spróbuj ponownie",
            genderMale: "Męska",
            genderFemale: "Żeńska"
        },
        ja: {
            country: "日本語",
            loadcanvasText: "分析中...",
            loadMore: "もっと見る！",
            areYouSure: "Watch the result?",
            recommendText: "その他の人気クイズ",
            shareFb: "シェア",
            replay: "もう一度お試しください",
            genderMale: "男性",
            genderFemale: "女性"
        },
        sv: {
            country: "Sweden",
            loadcanvasText: "Analyserar...",
            loadMore: "Visa mig mer!",
            areYouSure: "Watch the result?",
            recommendText: "Andra populära quizar",
            shareFb: "Dela",
            replay: "Försök igen",
            genderMale: "Man",
            genderFemale: "Kvinna"
        },
        el: {
            country: "Ελληνικά",
            loadcanvasText: "Ανάλυση...",
            loadMore: "Εμφάνισε μου περισσότερα!",
            areYouSure: "Watch the result?",
            recommendText: "άλλα δημοφιλή κουίζ",
            shareFb: "Κοινοποίηση",
            replay: "Προσπαθήστε Ξανά",
            genderMale: "Άνδρας",
            genderFemale: "Γυναίκα"
        },
        cs: {
            country: "čeština",
            loadcanvasText: "Probíhá analýza...",
            loadMore: "Ukažte mi více!",
            areYouSure: "Watch the result?",
            recommendText: "Další populární kvízy",
            shareFb: "Sdílet",
            replay: "Zkusit znovu",
            genderMale: "Muž",
            genderFemale: "Žena"
        },
        tl: {
            country: "Tagalog",
            loadcanvasText: "Analyzing...",
            loadMore: "Show Me More!",
            areYouSure: "Watch the result?",
            recommendText: "Iba pang mga sikat na quizzes",
            shareFb: "Share",
            replay: "Try Again",
            genderMale: "Male",
            genderFemale: "Female"
        }
    };
}